### ISSUE TITLE
Error while running the program

### ISSUE THREAD

**Issue by lu10539** [amazzalel-habib/TodoLangEditor#7]
The proxy was opened, but I get an error that the digital envelope routines are unsupported.
Setting `export NODE_OPTIONS=--openssl-legacy-provider` doesn't work because the node gets an invalid property value.
```
(base) ➜  blogpost-todo-lang-editor-master git:(a) ✗ npm --openssl-legacy-provider start 
Debugger attached.

> todolangeditor@1.0.0 start
> webpack-dev-server --hot --open

Debugger attached.
ℹ ｢wds｣: Project is running at http://localhost:8081/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/lucas/Downloads/blogpost-todo-lang-editor-master
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/webpack/lib/NormalModule.js:449:10)
    at /Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/webpack/lib/NormalModule.js:481:5
    at /Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/webpack/lib/NormalModule.js:342:12
    at /Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
Waiting for the debugger to disconnect...
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/webpack/lib/NormalModule.js:449:10)
    at /Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/webpack/lib/NormalModule.js:481:5
    at /Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/webpack/lib/NormalModule.js:342:12
    at /Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/lucas/Downloads/blogpost-todo-lang-editor-master/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.6.0
Waiting for the debugger to disconnect...
```

**Comment by webuniverseio** [comment]
Could this be related to node version?

**Comment by webuniverseio** [comment]
this works
  "scripts": {
    "start": "NODE_OPTIONS=--openssl-legacy-provider webpack-dev-server --hot --open",
  },
